services:
  - docker

script:
  - docker build --tag nixsgxsdk --file sgxsdk-with-prebuilt-ipp.Dockerfile .
  - docker build --tag nixsgxsdk --file sgxsdk.Dockerfile .
  - docker build --tag nixsgxsdk --file ipp.Dockerfile .

jobs:
  include:
    - stage: sgx sdk with prebuilt ipp-crypto lib
      name: sgxsdk-with-prebuilt-ipp
      script: docker build --tag sgxsdk-with-prebuilt-ipp --file sgxsdk-with-prebuilt-ipp.Dockerfile .
    - stage: sgx sdk with ipp-crypto built from source
      name: sgxsdk-with-ipp-built-from-source
      script: docker build --tag sgxsdk --file sgxsdk.Dockerfile .
    - stage: ipp-crypto library
      name: ipp-crypto
      script: docker build --tag ipp-crypto --file ipp.Dockerfile .
