version: '3.9'

services:
  ipp:
    image: nix-ippcrypto:local
    build:
      context: .
      target: ipp
    volumes:
      - ./ipp.nix:/usr/src/ipp.nix
      - ./nix:/usr/src/nix
  sgxsdk:
    image: nix-sgxsdk:local
    build:
      context: .
      target: sgxsdk
    devices:
      - /dev/isgx
    volumes:
      - ./sgxsdk.nix:/usr/src/sgxsdk.nix
      - ./shell.nix:/usr/src/shell.nix
      - ./nix:/usr/src/nix
      - ./SampleCode:/tmp/app
  sgxsdk-with-prebuilt-ipp:
    image: nix-sgxsdk-with-prebuilt-ipp:local
    build:
      context: .
      target: sgxsdk-with-prebuilt-ipp
    devices:
      - /dev/isgx
    volumes:
      - ./sgxsdk-with-prebuilt-ipp.nix:/usr/src/sgxsdk-with-prebuilt-ipp.nix
      - ./nix:/usr/src/nix
  rust-sgxsdk:
    image: nix-rust-sgx-sdk
    build:
      dockerfile: rust.Dockerfile
      context: .
    devices:
      - /dev/isgx
    volumes:
      - ./asldobjdump.nix:/usr/src/asldobjdump.nix
      - ./sgxsdk.nix:/usr/src/sgxsdk.nix
      - ./shell.nix:/usr/src/shell.nix
      - ./rust-sgx-sdk.nix:/usr/src/rust-sgx-sdk.nix
      - ./nix:/usr/src/nix
      - ./keys:/usr/src/keys
      - ./reproducibility_verifier.sh:/usr/src/reproducibility_verifier.sh
