version: '3.9'

services:
  ipp:
    image: nix-ippcrypto:local
    build:
      context: .
      target: build
      dockerfile: ipp.Dockerfile
    volumes:
      - ./nix:/usr/src/nix
      - ./ipp.nix:/usr/src/ipp.nix

  sgxsdk:
    image: nix-sgxsdk:local
    build:
      context: .
      target: build
      dockerfile: sgxsdk.Dockerfile
    devices:
      - /dev/isgx
    volumes:
      - ./nix:/usr/src/nix
      - ./sgxsdk.nix:/usr/src/sgxsdk.nix
      - ./shell.nix:/usr/src/shell.nix
      - ./SampleCode:/tmp/app

  sgxsdk-nomitigation:
    image: nix-sgxsdk-nomitigation:local
    build:
      context: .
      target: build
      dockerfile: Dockerfile
      args:
        nix_derivation: sgxsdk-nomitigation.nix
    devices:
      - /dev/isgx
    volumes:
      - ./nix:/usr/src/nix
      - ./sgxsdk-nomitigation.nix:/usr/src/sgxsdk-nomitigation.nix

  sgxsdk-with-prebuilt-ipp:
    image: nix-sgxsdk-with-prebuilt-ipp:local
    build:
      context: .
      target: build
      dockerfile: sgxsdk-with-prebuilt-ipp.Dockerfile
    devices:
      - /dev/isgx
    volumes:
      - ./sgxsdk-with-prebuilt-ipp.nix:/usr/src/sgxsdk-with-prebuilt-ipp.nix
      - ./nix:/usr/src/nix
  sgxsdk-nomitigation-with-prebuilt-ipp:
    image: sgxsdk-nomitigation-with-prebuilt-ipp:local
    build:
      context: .
      target: build
      dockerfile: Dockerfile
      args:
        nix_derivation: sgxsdk-nomitigation-with-prebuilt-ipp.nix
    devices:
      - /dev/isgx
    volumes:
      - ./sgxsdk-nomitigation-with-prebuilt-ipp.nix:/usr/src/sgxsdk-nomitigation-with-prebuilt-ipp.nix
      - ./nix:/usr/src/nix

  rust-sgxsdk:
    image: nix-rust-sgx-sdk
    build:
      dockerfile: rust.Dockerfile
      context: .
    devices:
      - /dev/isgx
    volumes:
      - ./asldobjdump.nix:/usr/src/asldobjdump.nix
      - ./sgxsdk.nix:/usr/src/sgxsdk.nix
      - ./shell.nix:/usr/src/shell.nix
      - ./rust-sgx-sdk.nix:/usr/src/rust-sgx-sdk.nix
      - ./nix:/usr/src/nix
      - ./keys:/usr/src/keys
      - ./reproducibility_verifier.sh:/usr/src/reproducibility_verifier.sh
